version: '3.9'

services:

  redis:
    image: redis:6.2.5-alpine
    container_name: redis
    restart: always
    ports:
      - 6379:6379
    volumes:
      - ./data:/data

  jobqueue:
    build: ./jobQueue
    command: npm i && npm start
    ports:
      - 3000:3000 

  jobqueueworker:
    build: ./jobProcessor
    command: npm i && npm start
    depends_on:
      - redis    

